dist: trusty

branches:
    only:
        - master
        - dev

language: python
python:
    - 3.6

cache:
    pip: true

install:
    - pip install -U -e .[dev]

script:
    - python setup.py test
