branches:
    only:
        - master
        - dev

environment:
    matrix:
        - PYTHON: "C:\\Python36-x64\\python.exe"

build_script:
    - "%PYTHON% -m pip install -U -e .[dev]"

test_script:
    - "%PYTHON% setup.py test"
