jobs:
  - job: "Build"
    displayName: 'Build Python SDK'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.11"
      - bash: |
          python --version
        displayName: 'Check python version'
      - bash: |
          python -m pip install -U pip
          python -m pip install build
          python -m build
        displayName: 'Build Python SDK'
